NODE_COLORS = {
    # Module Level
    'Module': 'lightblue',
    'Interactive': 'lightblue',
    'Expression': 'lightblue',
    'FunctionType': 'lightblue',
    # Statements
    'FunctionDef': 'lightgreen',
    'AsyncFunctionDef': 'lightgreen',
    'ClassDef': 'lightgreen',
    'Return': 'lightgreen',
    'Delete': 'lightgreen',
    'Assign': 'lightgreen',
    'AugAssign': 'lightgreen',
    'AnnAssign': 'lightgreen',
    'For': 'lightgreen',
    'AsyncFor': 'lightgreen',
    'While': 'lightgreen',
    'If': 'lightgreen',
    'With': 'lightgreen',
    'AsyncWith': 'lightgreen',
    'Match': 'lightgreen',
    'Raise': 'lightgreen',
    'Try': 'lightgreen',
    'TryStar': 'lightgreen',
    'Assert': 'lightgreen',
    'Import': 'lightgreen',
    'ImportFrom': 'lightgreen',
    'Global': 'lightgreen',
    'Nonlocal': 'lightgreen',
    'Expr': 'lightgreen',
    'Pass': 'lightgreen',
    'Break': 'lightgreen',
    'Continue': 'lightgreen',
    # Expressions
    'BoolOp': 'lightyellow',
    'NamedExpr': 'lightyellow',
    'BinOp': 'lightyellow',
    'UnaryOp': 'lightyellow',
    'Lambda': 'lightyellow',
    'IfExp': 'lightyellow',
    'Dict': 'lightyellow',
    'Set': 'lightyellow',
    'ListComp': 'lightyellow',
    'SetComp': 'lightyellow',
    'DictComp': 'lightyellow',
    'GeneratorExp': 'lightyellow',
    'Await': 'lightyellow',
    'Yield': 'lightyellow',
    'YieldFrom': 'lightyellow',
    'Compare': 'lightyellow',
    'Call': 'lightyellow',
    'FormattedValue': 'lightyellow',
    'JoinedStr': 'lightyellow',
    'Attribute': 'lightyellow',
    'Subscript': 'lightyellow',
    'Starred': 'lightyellow',
    'List': 'lightyellow',
    'Tuple': 'lightyellow',
    'Slice': 'lightyellow',
    # Names and Constants
    'Name': 'lightpink',
    'Constant': 'lightpink',
    # Operators (arithmetic, bitwise, matrix)
    'Add': 'orange',
    'Sub': 'orange',
    'Mult': 'orange',
    'Div': 'orange',
    'FloorDiv': 'orange',
    'Mod': 'orange',
    'Pow': 'orange',
    'LShift': 'orange',
    'RShift': 'orange',
    'BitOr': 'orange',
    'BitXor': 'orange',
    'BitAnd': 'orange',
    'MatMult': 'orange',
    # Comparison Operators
    'Eq': 'orange',
    'NotEq': 'orange',
    'Lt': 'orange',
    'LtE': 'orange',
    'Gt': 'orange',
    'GtE': 'orange',
    'Is': 'orange',
    'IsNot': 'orange',
    'In': 'orange',
    'NotIn': 'orange',
    # Boolean Operators
    'And': 'orange',
    'Or': 'orange',
    # Unary Operators
    'Invert': 'orange',
    'Not': 'orange',
    'UAdd': 'orange',
    'USub': 'orange',
    # Control Flow
    'If': 'plum',
    'For': 'plum',
    'While': 'plum',
    'Try': 'plum',
    'With': 'plum',
    'Match': 'plum',
    # Containers
    'List': 'lightgrey',
    'Dict': 'lightgrey',
    'Set': 'lightgrey',
    'Tuple': 'lightgrey',
    # Contexts
    'Load': 'lightgrey',
    'Store': 'lightgrey',
    'Del': 'lightgrey',
}

LEGEND = [
    ("Module Level", 'Module'),
    ("Statement", 'FunctionDef'),
    ("Expression", 'BinOp'),
    ("Name/Constant", 'Name'),
    ("<B>Operator</B><BR/>(arithmetic,<BR/>bitwise,<BR/>comparison,<BR/>boolean,<BR/>unary)", 'Add'),
    ("Control Flow", 'If'),
    ("<B>Container/Context</B><BR/>(lists,<BR/>dicts,<BR/>sets,<BR/>tuples,<BR/>Load/Store/Del)", 'List'),
] 